# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18cad4ffbd1786d816d2bd13cf9a3d002fc9f353be5e3ce1e7a95b2a79798ccfbf289548ab69d3db82d8ac5b22165bcae19400cf47dac88a2c8a84e34fca39ce

test:
  secret_key_base: 00fc41cfc1af2030fa8c62e0c1d9007b3b20a212d764292c8a74fee05d2f3f397b5b223466061f24db0cb16fb26f5bf439a0c569b3cedcdb12908dbecae79271

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
